//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metro.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici_Gorev_Iliskisi
    {
        public int Id { get; set; }
        public int GorevId { get; set; }
        public int KullaniciId_Gorevli { get; set; }
        public int KullaniciId_Yonetici { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual Gorev Gorev { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual Kullanici Kullanici1 { get; set; }
    }
}
