//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metro.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici_Iletisim_Bilgileri
    {
        public int Id { get; set; }
        public int KullaniciId { get; set; }
        public int IletisimTipiId { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual Iletisim_Tipi Iletisim_Tipi { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
