//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metro.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JiraEntities3 : DbContext
    {
        public JiraEntities3()
            : base("name=JiraEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Giris_Bilgileri> Giris_Bilgileri { get; set; }
        public virtual DbSet<Gorev> Gorev { get; set; }
        public virtual DbSet<Iletisim_Tipi> Iletisim_Tipi { get; set; }
        public virtual DbSet<Is_Onceligi> Is_Onceligi { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Kullanici_Gorev_Iliskisi> Kullanici_Gorev_Iliskisi { get; set; }
        public virtual DbSet<Kullanici_Iletisim_Bilgileri> Kullanici_Iletisim_Bilgileri { get; set; }
        public virtual DbSet<Kullanici_Pozisyon_Iliskisi> Kullanici_Pozisyon_Iliskisi { get; set; }
        public virtual DbSet<Pozisyon> Pozisyon { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    
        [DbFunction("JiraEntities3", "KullaniciBilgileri")]
        public virtual IQueryable<KullaniciBilgileri_Result> KullaniciBilgileri()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<KullaniciBilgileri_Result>("[JiraEntities3].[KullaniciBilgileri]()");
        }
    }
}
